### ISSUE TITLE
Add support for Gemini 

### ISSUE THREAD

**Issue by davidmigloz** [davidmigloz/pixels2flutter#17]
https://langchaindart.com/#/modules/model_io/models/chat_models/integrations/googleai

**Comment by sheyaln** [comment]
I'd love to take a stab at this, if you don't mind! 
Is there a contribution guide, or should I write some spaghetti and make a PR?

**Comment by davidmigloz** [comment]
Hey @Milksheyke!

Great to hear that you are interested in contributing to the project 🙂

At the moment I don't have any contribution guide, unfortunately. We can maybe discuss how to implement it here.

I already added support for Gemini on LangChain.dart, so the integration should be straightforward. We may need to think about how we adapt the UX flow to support different models (I would also like to add support for Ollama to run local models). Do you have any ideas?

**Comment by sheyaln** [comment]
I'm fairly new to cooperating on code, so please forgive me if I misunderstood the question and stating the obvious here.

I was thinking a dropdown with the supported models, where the displayed fields dynamically change based on the selected model.

<img width="753" alt="Screenshot 2024-01-07 at 2 28 48 PM" src="https://github.com/davidmigloz/pixels2flutter/assets/101238506/f4c673c4-18e2-49d1-ab17-edeff90cfe4c">

Based on the selected model, we execute the appropriate cubit event.
We could also use tabs instead of the dropdown so that the instructions, fields, layout, etc can be bundled together as a separate Widget for each supported model that display within _S3ApiKeys.

I've never worked with Ollama, but by local model, do you mean:
- A model running on the user's machine which they're using to visit the website, with the browser facilitating communication?
- A model running on the user's own server/cloud instance, with HTTP/Websockets for communication between pixel2flutter and the LLM based on the endpoint provided by the user?
- Both?

**Comment by davidmigloz** [comment]
sounds good!

With local models I mean that the models are running on the user's machine. There are a couple of multi-modal models that Ollama supports ([bakllava](https://ollama.ai/library/bakllava) and [llava](https://ollama.ai/library/llava)). Ollama server runs locally and exposes an API to interact with the model. 

Regarding your second point, some users would like to be able to proxy the calls to OpenAI/Google (https://github.com/davidmigloz/pixels2flutter/issues/2), so adding an option to customize the base URL/headers would be useful. We don't need to do it as part of this ticket, but good to have it in mind while we redesign the UI.

**Comment by tinoper** [comment]
Hey there, I'm catching up on this issue. I 'd like to help to add Gemini support to pixel2flutter. Have you made any progress on it ?

**Comment by davidmigloz** [comment]
hey @tinoper,

I didn't find time to work on this, unfortunately, so happy if you could take it over!

**Comment by tinoper** [comment]
Ok, I'll give it a try!
By the way, there is a discord link for LangChain.dart but it doesn't works. I have a question about ChatGoogleGenerativeAI in langchain_google package so it could be useful to join to discord LangChain community. By the way, great work!

**Comment by davidmigloz** [comment]
Awesome! This invite link should work: https://discord.gg/x4qbhqecVR

**Comment by tinoper** [comment]
Thank you, I'm in.
I found that ChatGoogleGenerativeAI doesn't have set method that the same openAI chat model already have. 
On the other hand, reading a thread where you were explaining that langchain dart were considering deprecating googleai_dart and using the official client google_generative_ai. Would it be better for Pixel2Flutter to try adding google_generative_ai and forget about langchain?

**Comment by davidmigloz** [comment]
Hey @tinoper ,

Indeed, those methods were missing from `ChatGoogleGenerativeAI`. I've just added them (https://github.com/davidmigloz/langchain_dart/pull/357).

I'm not planning to release a new version of LangChain.dart in the coming days, as I'm doing some refactoring that I want to release altogether. But you can depend on the commit that contains the API key getters/setters (I've pushed a [branch with the dependencies pointing to that commit](https://github.com/davidmigloz/pixels2flutter/commit/08da383e74438f9e35db58a823cba702ff7d6ff2), you can work on top of it).

One of the main points of LangChain is to provide a unified API for different LLM providers, which is something useful for this project. The migration from `googleai_dart` to `google_generative_ai` is something that will happen internally on LangChain.dart, it won't affect its public API.

**Comment by tinoper** [comment]
The ChatGoogleGenerativeAI class doesn't have the supported streaming method (line 198). Not sure if it's worth it considering they might switch to the official package soon.

**Comment by davidmigloz** [comment]
Ahh true, I forgot streaming was pending to be implemented. I'll take over the ticket to migrate `ChatGoogleGenerativeAI ` to the official client from @luisredondo (https://github.com/davidmigloz/langchain_dart/issues/332). I can quickly implement it tonight. I'll let you know when it's done.

**Comment by luisredondo** [comment]
Hey @davidmigloz! Sorry, I have not prioritized this work; I have been very busy! I made an initial effort some time ago. In case it helps you, here is that attempt: https://github.com/luisredondo/langchain_dart/pull/1

Let me know if I can help with something.

**Comment by davidmigloz** [comment]
@tinoper `ChatGoogleGenerativeAI` now supports streaming (https://github.com/davidmigloz/langchain_dart/pull/360), I've updated the dependencies in the [`google_ai`](https://github.com/davidmigloz/pixels2flutter/commits/google_ai/) branch to point to the latest LangChain.dart commit. Hopefully there isn't more blockers!

**Comment by davidmigloz** [comment]
@luisredondo no worries! I imagined that. I've halted the migration as the official client is still not as feature complete as `googleai_dart` (https://github.com/davidmigloz/langchain_dart/issues/332#issuecomment-2033099926). Thanks for your work!

**Comment by tinoper** [comment]
@davidmigloz Thank you for your quick response. Now I have the stream, but I'm encountering an issue when mapping it similar to what `GenerateCodeFromImageUseCase` class does. The mapper located in [langchain_google/lib/src/chat_models/google_ai/mappers.dart](https://github.com/luisredondo/langchain_dart/blob/main/packages/langchain_google/lib/src/chat_models/google_ai/models/mappers.dart) is giving me the error message ***'Google AI does not support system messages at the moment. Attach your system message in the human message.'***

It's not clear to me if this is something we should address in the mapper or in the content we're sending. I'm trying to send it in the same way we do with the OpenAI option for consistency.

**Comment by davidmigloz** [comment]
@tinoper step by step 😄

Google models don't support system messages (messages with role `system`) yet, as other providers like OpenAI do.
We should probably define two prompt templates, the existing one for GPT-4 and a new one for Gemini using a single human message.

Anyway, the way you prompt Gemini is normally slightly different than the way you prompt GPT-4. OpenAI models are quite good at following instructions, whereas Google models are better at following examples. So we'll have to experiment until we find a good prompt for Gemini.

**Comment by davidmigloz** [comment]
@tinoper the new release of LangChain.dart is out, so there's no need to override the dependencies anymore
https://github.com/davidmigloz/langchain_dart/releases/tag/langchain-v0.5.0

**Comment by tinoper** [comment]
Hey @davidmigloz , big changes in LangChain.dart then but before updating I'd like to try getting something by querying Gemini. It's not clear to me if PromptValue is able to handle the query without ChatMessage.system(_systemPrompt). If that's the case, I can only remove that line and include another complete prompt in ChatMessage.human.

Maybe to avoid making too much noise here, I'll contact you via Discord if you agree.

I've tried using the Google client outside of here to see how it handles it and the prompt should change quite a bit but it could serve as an alternative.

**Comment by davidmigloz** [comment]
Hey @tinoper ,

Yes, `PromptValue` doesn't require a system message. You can include everything as a human message.

I've quickly integrated `ChatGoogleGenerativeAI` provider in the `generate_code_from_image.dart` use case . I've pushed the changes in this branch: https://github.com/davidmigloz/pixels2flutter/commit/1891d236cac722b565f63922d41d4f278f1a20c8

I've tested it hardcoding my Google AI key, and it seems to be working fine. You can take it over from there 🙂

What's missing:
- Update the UI to allow selecting OpenAI or GoogleAI
- Allow to enter Google AI key
- Optimize Gemini prompt (I've just copy-pasted the one from OpenAI)

Thanks for your work and feel free to contact me on Discord!

**Comment by ps6067966** [comment]
> Hey @tinoper ,
> 
> Yes, `PromptValue` doesn't require a system message. You can include everything as a human message.
> 
> I've quickly integrated `ChatGoogleGenerativeAI` provider in the `generate_code_from_image.dart` use case . I've pushed the changes in this branch: [1891d23](https://github.com/davidmigloz/pixels2flutter/commit/1891d236cac722b565f63922d41d4f278f1a20c8)
> 
> I've tested it hardcoding my Google AI key, and it seems to be working fine. You can take it over from there 🙂
> 
> What's missing:
> 
> * Update the UI to allow selecting OpenAI or GoogleAI
> * Allow to enter Google AI key
> * Optimize Gemini prompt (I've just copy-pasted the one from OpenAI)
> 
> Thanks for your work and feel free to contact me on Discord!

Wow

**Comment by tinoper** [comment]
@davidmigloz , sorry for the hold-up.  What do you think of a segmented button like this for entering the API key? 
We can always add more options later, after GoogleAI.

<img width="880" alt="Screenshot 2024-05-03 at 3 24 06 PM" src="https://github.com/davidmigloz/pixels2flutter/assets/4380484/4957059c-b7e6-48c2-9de5-d4a1ff9a7098">
<img width="838" alt="Screenshot 2024-05-03 at 3 24 00 PM" src="https://github.com/davidmigloz/pixels2flutter/assets/4380484/87f2ca7a-5e04-44c2-ab06-2b5d48abdcec">

**Comment by davidmigloz** [comment]
@tinoper Looks good! Thanks for following up

**Comment by davidmigloz** [comment]
Hey @tinoper ,

Did you manage to get it working? I can take it over from where you are otherwise. I want to add support for Anthropic as well.

**Comment by tinoper** [comment]
I haven't gotten to it yet, but I'll make time to review it today and add it over the weekend. I'll let you know if I have any questions before then. Does that work for you?

**Comment by davidmigloz** [comment]
Awesome! Yes, that's perfect

**Comment by davidmigloz** [comment]
Google AI is finally available as a provider in https://pixels2flutter.dev/ 🥳
<img width="872" alt="image" src="https://github.com/user-attachments/assets/032e9775-cfcf-48bd-bcc4-65fcd3e31a70">

Thanks again for your work @tinoper!!

I'll add support for Anthropic this week as well.
