### ISSUE TITLE
Sweepy : Zmień generowanie do flutter w generowanie do flutterflow.io + instrukcje po polsku krok po kroku każdego elementu.!

### ISSUE THREAD

**Issue by lasotaagency** [davidmigloz/pixels2flutter#28]
Sweepy : Zmień kod tak, aby był były po polsku, a kod, który został wygenerowany był dla flutterflow.io a nie flutter. czyli muszą mieć pliki niestandardowego kodu, funkcje i niestandardowy widget kodu oraz schemat supabase.io oraz udostępnianie jak każdy pojedyńczy element interfejsu w flutterflow.io z wszystkimi co niezbędnymi jak dla kogoś, kto się nie zna i do każdego elementu utworu z pliku .md z przekazania po polsZmień kod tak, aby był były po polsku, a kod, który został wygenerowany był dla flutterflow.io a nie flutter. czyli muszą mieć pliki niestandardowego kodu, funkcje i niestandardowy widget kodu oraz schemat supabase.io oraz udostępnianie jak każdy pojedyńczy element interfejsu w flutterflow.io z wszystkimi co niezbędnymi jak dla kogoś, kto się nie zna i do każdego elementu utworu z pliku .md z przekazania po polski. jak podstawowy klasy ekspert i mentor w programowaniu w niskim kodzie flutterflow.io z 20 doświadczeniamiki. jak podstawowy klasy ekspert i mentor w programowaniu w niskim kodzie flutterflow.io z 20 letnim doświadczeniem

**Comment by lasotaagency** [comment]
sweep : help

**Comment by davidmigloz** [comment]
Hey @lasotaagency,

Could you maybe try these experiments in your own fork so that we don't pollute this repo? 
Thanks!
