### ISSUE TITLE
I would like to ask how to generate a completed App

### ISSUE THREAD

**Issue by motaionx** [davidmigloz/pixels2flutter#39]
I would like to ask how to generate a completed App. If it is an application with more than ten interfaces, how can it be generated at once?

**Comment by davidmigloz** [comment]
Hello @motaionx ,

At the moment, pixels2flutter only supports one-shot generations. For generating applications iteratively you may want to try some more advanced solutions like 
- https://github.com/gpt-engineer-org/gpt-engineer
- https://github.com/sweepai/sweep
- https://www.cognition-labs.com
- etc.
