### ISSUE TITLE
images generated on https://corsproxy.io/

### ISSUE THREAD

**Issue by noname29** [davidmigloz/pixels2flutter#49]
https://corsproxy.io/ images generated return "You have been blocked." How can I retrieve those images and possibly add it to my project locally after ?

**Comment by davidmigloz** [comment]
Hey @noname29,

If the screen has many images, corsproxy.io may block some of the requests. 
If you don't need to preview the screen in DartPad, you can just remove the proxy and use the image URL directly (or download the image and add it to your assets or host them in your own server).

~~https://corsproxy.io/?~~ https%3A%2F%2Foaidalleapiprodscus.blob.core.windows.net%2Fprivate%2Forg-8fhNTBqQlNWc3VoCLZoRG36B%2Fuser-HnlrdJSa1BiX9ouoYGjVo9JW%2Fimg-Hw6k5qRYo5JUjwzHHVXtB0qV.png...
