### ISSUE TITLE
dart flutter : No named parameter with the name 'primary'

### ISSUE THREAD

**Issue by noname29** [davidmigloz/pixels2flutter#50]
https://api.flutter.dev/flutter/material/TextButton/styleFrom.html

styleFrom doesn't have primary parameter anymore. Can we update this to work better ? 

```
../../../flutter/packages/flutter/lib/src/material/text_button.dart:146:22: Context: Found this candidate, but the arguments don't match.
  static ButtonStyle styleFrom({
                     ^^^^^^^^^
lib/main.dart:93:19: Error: No named parameter with the name 'primary'.
                  primary: Theme.of(context).colorScheme.primary,
                  ^^^^^^^
```

**Comment by davidmigloz** [comment]
Hey @noname29,

The project is compiled against the latest Flutter stable version (3.19.3). 
I cannot reproduce your error, you can see in [the CICD that it is building properly](https://github.com/davidmigloz/pixels2flutter/actions/runs/8322492041).

Which Flutter version are you using?
