### ISSUE TITLE
flutter_switch package doesn't exist

### ISSUE THREAD

**Issue by noname29** [davidmigloz/pixels2flutter#51]
on this page after converting to code https://pixels2flutter.dev/gist/

I get this error 

`Targer of URI doesn't exist: 'package:flutter_switch/flutter_switch.dart';`

on this line

`import 'package:flutter_switch/flutter_switch.dart';`

you said this is running flutter 3.9 ?

**Comment by davidmigloz** [comment]
`flutter_switch` seems to be a 3rd party package (https://pub.dev/packages/flutter_switch). https://dartpad.dev only supports a very limited set of 3rd party packages, among which `flutter_switch` is not part of.

You can take the generated code to Android Studio / VSC and add `flutter_switch` to the pubspec, it should solve the error.
